version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          working_directory: Cloudlib/
          name: Check project consistency
          command: |
            dotnet build
            dotnet pack  --output artifacts
            dotnet nuget push "artifacts/*.nupkg" --skip-duplicate --api-key $NUGET_API_KEY --source "https://api.nuget.org/v3/index.json"

workflows:
  check-code-integrity:
    jobs:
      - build
    when:
      or:
        - equal: [ main, << pipeline.git.branch >> ]
        - matches:
            pattern: "^release"
            value: << pipeline.git.branch >>

